-- MySQL Script generated by MySQL Workbench
-- Thu Aug 24 15:13:56 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `biblioteca` DEFAULT CHARACTER SET utf8 ;
USE `biblioteca` ;

-- -----------------------------------------------------
-- Table `biblioteca`.`Alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`Alunos` (
  `id_Aluno` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `cpf`  VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `telefone` INT NOT NULL,
  `celular` INT NOT NULL,
  `data-nascimento` DATE NOT NULL,
  PRIMARY KEY (`id_Aluno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`Livros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`Livros` (
  `id_Livro` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '\n\n\n',
  `titulo` VARCHAR(100) NOT NULL,
  `autor` VARCHAR(100) NOT NULL,
  `numero_pagina` INT NOT NULL,
  `preco` DECIMAL(10,2) NOT NULL,
  `ano_publicacao` INT NOT NULL,
  `isbn`  VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_Livro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`Emprestimos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`Emprestimos` (
  `Alunos_id_Alunos` INT UNSIGNED NOT NULL,
  `Livros_id_Livros` INT UNSIGNED NOT NULL,
  `data_emprestimo` DATETIME NOT NULL,
  `data_devolucao` DATE NOT NULL,
  PRIMARY KEY (`Alunos_id_Alunos`, `Livros_id_Livros`),
  INDEX `fk_Alunos_has_Livros_Livros1_idx` (`Livros_id_Livros` ASC) VISIBLE,
  INDEX `fk_Alunos_has_Livros_Alunos_idx` (`Alunos_id_Alunos` ASC) VISIBLE,
  CONSTRAINT `fk_Alunos_has_Livros_Alunos`
    FOREIGN KEY (`Alunos_id_Alunos`)
    REFERENCES `biblioteca`.`Alunos` (`id_Aluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Alunos_has_Livros_Livros1`
    FOREIGN KEY (`Livros_id_Livros`)
    REFERENCES `biblioteca`.`Livros` (`id_Livro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`Usuarios` (
  `id_Usuarios` INT UNSIGNED ZEROFILL NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  `perfil` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id_Usuarios`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
